services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${pass}
      POSTGRES_DB: ${name}
    container_name: otso_db
    volumes:
      - ./postgres:/var/lib/postgresql/data